#!/bin/bash

# make sure all necessary env vars are set
source ./env-default.sh \
&& ./envsub < ./${NGINX_CONFIG_TEMPLATE} > /etc/nginx/nginx.conf \
&& cat /etc/nginx/nginx.conf \
&& chown -R nginx:nginx /usr/local/share/www \
&& chmod -R 755 /usr/local/share/www \
&& chown -R nginx:nginx /www \
&& chmod -R 755 /www;
# && install -m644 /www/* /usr/local/share/www \

nginx -g "daemon off;"
